services:
  app_rolling:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    deploy:
      replicas: 3
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app_rolling