name: Rolling Deployment

on:
  push:
    tags:
      - "v*"

env:
  SSH_HOST: ${{  secrets.SSH_HOST  }}
  SSH_USERNAME: ${{secrets.SSH_USERNAME}}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: ${{secrets.DOCKER_REPO}}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{env.DOCKER_REPO}}:${{github.ref_name}}
            ${{ env.DOCKER_USERNAME }}/${{env.DOCKER_REPO}}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{env.SSH_PRIVATE_KEY}}
          source: "deploy.sh"
          target: rolling/

      - name: Executing deploy script 
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{env.SSH_PRIVATE_KEY}}
          script: |
            cd rolling/
            echo "Running Deploy Script"
            chmod +x deploy.sh
            sudo DOCKER_USERNAME=${{ env.DOCKER_USERNAME }} TAG=${{ github.ref_name }} DOCKER_REPO=${{env.DOCKER_REPO}} ./deploy.sh

